### PR TITLE
WIP: Add initial UDP transport

### PR DESCRIPTION
**Pull request by ghost**
This doesn't even build yet, but I'm close. Comments very welcome. Next up is figuring out the relationship with go-peerstream, and adding the WriteMsg() and SetMsgHandler() interface to go-libp2p-swarm.

### CODE REVIEW

**Comment by whyrusleeping** [comment]
perhaps the transport and packet-transport interfaces should be separate?

We can have a package 'go-packet-transport' or something.

**Comment by whyrusleeping** [comment]
Aside from a preference to have the packet interfaces be in a repo separate from the streaming interfaces, this LGTM

**Comment by whyrusleeping** [comment]
(merge as you see fit)

**Comment by ghost** [comment]
Gonna make a new PR here

**Pull request closed without merging**
